-- MySQL Script generated by MySQL Workbench
-- Tue May 12 12:39:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema csc_courses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csc_courses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csc_courses` DEFAULT CHARACTER SET utf8mb4 ;
USE `csc_courses` ;

-- -----------------------------------------------------
-- Table `csc_courses`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc_courses`.`courses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `course_no` VARCHAR(10) NULL DEFAULT NULL,
  `hours` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `csc_courses`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc_courses`.`rooms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `room_no` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `csc_courses`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc_courses`.`sections` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `course_id` INT(11) NULL DEFAULT NULL,
  `section_no` VARCHAR(5) NULL DEFAULT NULL,
  `no_of_days` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sections_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `csc_courses`.`courses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `csc_courses`.`time_slot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc_courses`.`time_slot` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `section_id` INT(11) NULL DEFAULT NULL,
  `room_id` INT(11) NULL DEFAULT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  `duration` INT(11) NULL DEFAULT NULL,
  `day` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `time_slot_ibfk_1`
    FOREIGN KEY (`section_id`)
    REFERENCES `csc_courses`.`sections` (`id`),
  CONSTRAINT `time_slot_ibfk_4`
    FOREIGN KEY (`room_id`)
    REFERENCES `csc_courses`.`rooms` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 841
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
